### ISSUE TITLE
Sending transaction fails with gas price less than block base fee

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-bridge#39]
```
2021-09-13 15:04: debug: HomeBridge tx error -> Error: Returned error: err: max fee per gas less than block base fee: address 0xa27243046e16ee596D19Ff3091719160527e469a, maxFeePerGas: 120000000000 baseFee: 144771606946 (supplied gas 13242564)
    at Object.ErrorResponse (/home/deploy/giveth-bridge/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/deploy/giveth-bridge/node_modules/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (/home/deploy/giveth-bridge/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/deploy/giveth-bridge/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/deploy/giveth-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/deploy/giveth-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/deploy/giveth-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  data: null
} undefined

```

**Comment by aminlatifi** [comment]
#32
